title: Pandora Blogx
description: My unpredictable box of thoughts, that might have my personal projects and playground, my thoughts and learinings.
author: Leo Souza Mattos
logo: /assets/images/mypic.jpg
github: https://github.com/leonardo-s-mattos
about: Senior Engineering Manager

baseurl: "/pandora-blogx"
#url: "http://localhost:4000"
url: "https://leonardo-s-mattos.github.io"


allowsearch: true

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#mattos_leonardo
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
